// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eyyyldcicfbssregnqfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV5eXlsZGNpY2Zic3NyZWducWZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2Mjg0MTYsImV4cCI6MjA2MjIwNDQxNn0.xLdQxh450yfZaeuRnan5sCLQ9zh69jbDNhimCwZYUTU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);